name: baselib
description: dev common lib
version: 0.1.2
homepage: https://gitee.com/Mocaris/flutter-baselib.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #https://pub.dev/packages/get
  get: ^4.3.8
  get_storage: ^2.0.3
  flutter_html: ^2.1.2
  package_info: ^2.0.2
  flutter_native_image: ^0.0.6+1
  wechat_assets_picker: ^6.1.2
  wechat_camera_picker: ^2.4.2
  image_gallery_saver: ^1.6.9
  cached_network_image: ^3.1.0
  permission_handler: ^8.1.6
  common_utils: ^2.0.2
  flutter_swiper_null_safety: ^1.0.2
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.3
  webview_flutter: ^2.0.14
  url_launcher: ^6.0.9
  dotted_line: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
